### ISSUE TITLE
Workforce percent dont work

### ISSUE THREAD

**Issue by mcailleauxgreenskin** [crissian/x4#97]
Hello

Since the last version, the workforce percent dont work anymore, products amounts are not update by changing the workforce percent

![image](https://user-images.githubusercontent.com/131990144/234910058-fba9aad3-24c6-4a8e-ae46-e106e6108563.png)

![image](https://user-images.githubusercontent.com/131990144/234910167-37e9b410-b94c-49e8-a82b-ef950d628eef.png)

**Comment by Stummi** [comment]
Hey, just want to drop a message that I implemented a Fix for this issue [here](https://github.com/crissian/x4/pull/99), which you can see/test on my forks deployment [here](https://stummi.github.io/x4/)

**Comment by theneofusion** [comment]
Has the change been pushed to the site?
I ask because this still doesn't work properly:
![workforce](https://user-images.githubusercontent.com/113138626/235708949-132c6dc4-ebb3-4ddc-8460-70fba7b6b98f.png)

Note the manually lowered Actual Workforce but the unchanged (maxed) production efficiency and ration/med supplies usage.

**Comment by crissian** [comment]
I didn’t deploy it yet. I’ll deploy it when I find the time

**Comment by crissian** [comment]
This doesn't seem to work as expected. I'm sure "it works on your machine"

**Comment by mcailleauxgreenskin** [comment]
Hello, 

It's worse, now every time we add a housing module, the percentage is different :'(

![image](https://user-images.githubusercontent.com/131990144/236306855-aae64f5c-5fdb-4892-a678-86054121f81d.png)

![image](https://user-images.githubusercontent.com/131990144/236307040-f4c9a37f-09d1-420e-b112-b46e416accf5.png)

![image](https://user-images.githubusercontent.com/131990144/236307243-d1104f37-252c-49e2-953f-dbb80a771f77.png)

**Comment by LittlDog** [comment]
Doesn't wanted to open a new topic for it, since this is kinda releated.

Could you add an option to manually add Workforce when adding a Habitat without any other Modules?

**Comment by Stummi** [comment]
Hey, I am really sorry, it seems like my PR introduced a bug with the calculation (I fixed it on my branch, but the PR got already merged in the meantime). I will provide another one to fix this issues

**Comment by elidiak** [comment]
@Stummi Did confirm that your version works. I'll wait for crissian to merge
